name: 'Jira Check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize
      - reopened

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '(DTCRPACCT)\w+(:)[\w\s]+' # Regex the title should match.
        min_length: 5 # Min length of the title
        max_length: 100 # Max length of the title
